//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudWithAjax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int sID { get; set; }
        public Nullable<int> cID { get; set; }
        public string sName { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
